const colors = [
	'#000000',
	'#FFFFFF',
	'#F5F5F5',
	'#EEEEEE',
	'#CCCCCC',
	'#999999',
	'#666666',
	'#333333',
	'#1E1E21',
] as const

const sizes = [10, 12, 14, 16, 18, 20, 24, 28, 32, 36, 40, 48, 56, 64] as const

export default {
	background: {
		type: 'BACKGROUND',
		label: '$label.background.design',
		colors,
		defaults: {},
	},
	gallery_navigation: {
		type: 'TOGGLE',
		label: '$label.gallery_navigation.design',
		defaults: {
			enabled: true,
		},
	},
	favorite_button: {
		type: 'TOGGLE',
		label: '$label.favorite_button.design',
		defaults: {
			enabled: true,
		},
	},
	breadcrumbs: {
		type: 'TEXT',
		label: '$label.breadcrumbs.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 16,
			bold: false,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	product_title: {
		type: 'TEXT',
		label: '$label.product_title.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.title',
			size: 32,
			bold: false,
			italic: false,
			color: 'global.color.title',
			visible: true,
		},
	},
	product_subtitle: {
		type: 'TEXT',
		label: '$label.product_subtitle.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 14,
			bold: false,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	product_price: {
		type: 'TEXT',
		label: '$label.product_price.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.title',
			size: 32,
			bold: false,
			italic: false,
			color: 'global.color.title',
			visible: true,
		},
	},
	product_compare_price: {
		type: 'TEXT',
		label: '$label.product_compare_price.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 18,
			bold: false,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	product_option_labels: {
		type: 'TEXT',
		label: '$label.product_option_labels.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 14,
			bold: true,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	quantity: {
		type: 'TEXT',
		label: '$label.quantity.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 14,
			bold: true,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	product_details: {
		type: 'TEXT',
		label: '$label.product_details.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 16,
			bold: false,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	product_sku: {
		type: 'TOGGLE',
		label: '$label.product_sku.design',
		defaults: {
			enabled: true,
		},
	},
	product_stock: {
		type: 'TOGGLE',
		label: '$label.product_stock.design',
		defaults: {
			enabled: true,
		},
	},
	product_attributes: {
		type: 'TOGGLE',
		label: '$label.product_attributes.design',
		defaults: {
			enabled: true,
		},
	},
	product_description: {
		type: 'TOGGLE',
		label: '$label.product_description.design',
		defaults: {
			enabled: true,
		},
	},
	share: {
		type: 'TEXT',
		label: '$label.share.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 14,
			bold: false,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	add_to_cart: {
		type: 'BUTTON',
		label: '$label.add_to_cart.design',
		colors,
		defaults: {
			appearance: 'SOLID',
			font: 'global.fontFamily.body',
			size: 'MEDIUM',
			shape: 'PILL',
			color: 'global.color.button',
			visible: true,
		},
	},
	related_products_background: {
		type: 'BACKGROUND',
		label: '$label.related_products_background.design',
		colors,
		defaults: {},
	},
	related_products_title: {
		type: 'TEXT',
		label: '$label.related_products_title.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.title',
			size: 32,
			bold: false,
			italic: false,
			color: 'global.color.title',
			visible: true,
		},
	},
	related_products_subtitle: {
		type: 'TEXT',
		label: '$label.related_products_subtitle.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 16,
			bold: false,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	related_product_name_price: {
		type: 'TEXT',
		label: '$label.related_product_name_price.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 16,
			bold: false,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	related_product_rating: {
		type: 'TEXT',
		label: '$label.related_product_rating.design',
		colors,
		sizes,
		defaults: {
			font: 'global.fontFamily.body',
			size: 16,
			bold: false,
			italic: false,
			color: 'global.color.body',
			visible: true,
		},
	},
	related_product_ribbon: {
		type: 'TOGGLE',
		label: '$label.related_product_ribbon.design',
		defaults: {
			enabled: true,
		},
	},
} as const
